### ISSUE TITLE
App Wifi not showing 

### ISSUE THREAD

**Issue by Awakedewe** [Rparadise-Team/Koriki#22]
### What happened?

After install koriki v1. 3 my WiFi stuck connection.. Go back to onion is WiFi stuck scanning. Try original firmware stuck scanning. Maybe my WiFi is broken. 
Maybe anyone have to solve my WiFi miyoo mini plus.? 
![IMG_20230718_104445](https://github.com/Rparadise-Team/Koriki/assets/104120561/0d96cec9-f41c-4c36-8157-4b2f65135ae7)

### Version

v1.3

**Comment by Ninoh-FOX** [comment]
Do you have the console updated with the ofw?

**Comment by Ninoh-FOX** [comment]
Try this, erase the save networks and set the networks again.

**Comment by Ninoh-FOX** [comment]
maybe you set network in stock, put off the network in stock and set this in koriki.
