### ISSUE TITLE
Please add samba support

### ISSUE THREAD

**Issue by DocMAX** [Rparadise-Team/Koriki#23]
### What happened?

Thanks!

### Version

v1.0

**Comment by Ninoh-FOX** [comment]
are you talking about miyoomini or rg35xx?

**Comment by Ninoh-FOX** [comment]
Why samba if you have ftp?

**Comment by DocMAX** [comment]
> Why samba if you have ftp?

no logins, directly run roms on pcs, better windows integration,...

**Comment by DocMAX** [comment]
> 

MiyooMini+

**Comment by Ninoh-FOX** [comment]
I sorry, But I don't put samba support in koriki
