### ISSUE TITLE
GBA no carga saves

### ISSUE THREAD

**Issue by BluePenguinBomber** [Rparadise-Team/Koriki#25]
### What happened?

Hola!

últimamente he estado jugando Pokémon en Koriki, todo iba bien hasta que salvé la partida ingame. El archivo .sav aparece en la carpeta correspondiente sin embargo no carga. Leí que se debía de cambiar la carpeta con el .sav y tampoco.

### Version

v1.0

**Comment by Ninoh-FOX** [comment]
rg35xx o miyoomini?

**Comment by BluePenguinBomber** [comment]
miyoo mini

**Comment by Ninoh-FOX** [comment]
Pues a mi me va todos los saves de pokemon tanto en gpsp, gpsp_plus, mgba y mgba_plus, y no son archivos sav, este los lee en formato srm
