### ISSUE TITLE
AtariST does not work

### ISSUE THREAD

**Issue by GtrevizeG** [Rparadise-Team/Koriki#27]
### What happened?

hello, on the Miyoo the system is not showing even if I have roms in the right folder (I have roms in zip files) + in the wiki the info seems to be incorrect (wrong supported extension). thanks for looking at this :) 

### Version

v1.0

**Comment by Ninoh-FOX** [comment]
I am test Atari ST with the core Hatari and the roms in zip work fine

But I see that Atari ST is not include in Koriki launchers

**Comment by GtrevizeG** [comment]
hello, yes I have the tos.img but as you said I don't see atari ST in the list of proposed system in the launcher when I'm on my Miyoo.

**Comment by Ninoh-FOX** [comment]
Because the team not maked a section for Atari STX

**Comment by Ninoh-FOX** [comment]
well, I see the problem, Atary ST is set, but not have 7z and zip files in the list, this will fixed in the next release

**Comment by GtrevizeG** [comment]
great. thank you !

**Comment by DocMAX** [comment]
I have .zip files with .ipf files in it. it loads to a green workbench with floppy a and b symbols, but there is no disk. how does this emu work?
