### ISSUE TITLE
SGFX as separated system 

### ISSUE THREAD

**Issue by GtrevizeG** [Rparadise-Team/Koriki#28]
### What happened?

I  understand SGFX seems to be managed by the PCE section but it would be great to be able to have a separated system if possible (like in batocera and others. request in on Miyoo. thank you for your time and effort :)

### Version

v1.0

**Comment by Ninoh-FOX** [comment]
the same that anothes issue, is very work make news sections. maybe in a new release.

**Comment by GtrevizeG** [comment]
that would be really appreciated :)
