### ISSUE TITLE
M"u needs to be hide in rom list

### ISSUE THREAD

**Issue by GtrevizeG** [Rparadise-Team/Koriki#29]
### What happened?

hello, I'm trying to use m3u files for psx multiple games. the problem is that when I display the list of games on my Miyoo+ the sytem displays all the discs + the m3u file. Is there a way to  display the consolidated view (meaning the m3u without displaying all the CD). 

ex : 
Chrono Cross (USA) (Disc 1).chd
Chrono Cross (USA) (Disc 2).chd
Chrono Cross (USA).m3u

The list in the system is displaying these 3 files. would be great to only see one :)

thank you / let me know if this is not clear enought :)

### Version

v1.0

**Comment by Ninoh-FOX** [comment]
This is because this list the two extension, is necessary if you have a single rom.

**Comment by dem1980** [comment]
You could also make a directory /Roms/PS-MULTI/ where you have only the *.chd files.
Then you put the *.m3u in the /Roms/PS/ directory with the paths : 
```
../PS-MULTI/Chrono Cross (USA) (Disc 1).chd
../PS-MULTI/Chrono Cross (USA) (Disc 2).chd
```

**Comment by Ninoh-FOX** [comment]
Yeah, do you have the /ROMS/PS-DATA for put inside the disk for m3u from /ROMS/PS
