### ISSUE TITLE
MAME: No sound after resume from save state

### ISSUE THREAD

**Issue by DocMAX** [Rparadise-Team/Koriki#42]
I played Bubble Bobble. Save states with sound work if i begin the game. If i close the emulator and open again after loading the same save state there is no sound anymore.

### Version

v1.4.1, Miyoo Mini +

**Comment by Ninoh-FOX** [comment]
This is a problem from mame and not have solution for now.

https://forums.libretro.com/t/no-audio-after-load-state-mame/26440

**Comment by Ninoh-FOX** [comment]
This is a problem from mame and not have solution for now.

https://forums.libretro.com/t/no-audio-after-load-state-mame/26440

**Comment by DocMAX** [comment]
Ahh, good link, i see... :-(
